### ISSUE TITLE
 When Flag is ‘json’ type,it can not use '[]' as flag value.

### ISSUE THREAD

**Issue by Orlando-li** [FeatureProbe/FeatureProbe#406]
**Describe the bug**
When the flag is of JSON type, if the value of the flag is square brackets [], the backend program will report an error and will not be able to notify the server to update the flag or retrieve the flag information.

**To Reproduce**
1. Go to config a ‘json’ type flag
<img width="1385" alt="image" src="https://github.com/FeatureProbe/FeatureProbe/assets/33117158/37fc9293-b919-449e-8339-c04880b1b426">  
2.api can not get this flag
<img width="897" alt="image" src="https://github.com/FeatureProbe/FeatureProbe/assets/33117158/147a9296-f0e8-4c00-a9d3-dabdae78b41f">  
3.backend server error log:
`Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"[]"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:222)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:457)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at io.featureprobe.api.base.util.JsonMapper.toObject(JsonMapper.java:40)
	... 48 common frames omitted`

**Comment by Orlando-li** [comment]
I think this error because of [] can not cast to Map.class, we need to add a new util function to hanlder json type.
![image](https://github.com/FeatureProbe/FeatureProbe/assets/33117158/822acf2b-b7b6-4d94-a3b8-b970b9b9cb4d)
